#!/bin/bash

#
# Modification History
#
# 2007-November-12    Jason Rohrer
# Copied from Cultivation.
#


cd gamma256/gameSource



echo "Building Passage..."

make



cd ../..

cp gamma256/gameSource/Passage.* ./www/
cp gamma256/documentation/Readme.txt ./www/

echo "Visit www/Passage.html in a browser to play."




